version: '3.8'

services:
  app:
    build: ./app
    container_name: linux-zero-to-hero_app
    volumes:
      - ./app/logs:/var/log/myapp
    ports:
      - "5000:5000"

  nginx:
    image: nginx:stable
    container_name: linux-zero-to-hero_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
